---
preuzimanje.do: 01.05.2023
OpenWeatherMap.apikey: c109885dbd5bf5de330c17df72166777
preuzimanje.od: 01.01.2023
LocationIQ.apikey: pk.1d5e047331d971eb32568a39f1795d28
OpenSkyNetwork.lozinka: chelsea1003
ciklus.trajanje: '300'
aerodromi.sakupljanje: EDDF
OpenSkyNetwork.korisnik: petarmatisic
