---
aplikacija.godina: '2023.'
stranica.brojRedova: '15'
aplikacija.verzija: '1.0'
autor.ime: Petar
autor.predmet: NWTiS
autor.prezime: Matišić
adresa.wa_1: http://200.20.0.4:8080/pmatisic_zadaca_2_wa_1/api/
