SELECT ADM.COUNTRY, MAX(ADM.DIST_CTRY) AS MAX_DIST_CTRY
FROM AIRPORTS_DISTANCE_MATRIX ADM
WHERE ADM.ICAO_FROM = 'EDDF'
GROUP BY ADM.COUNTRY
ORDER BY MAX_DIST_CTRY DESC
LIMIT 1;

SELECT * FROM PUBLIC.LETOVI_POLASCI;

SELECT DISTINCT ICAO_FROM, ICAO_TO, DIST_TOT
FROM AIRPORTS_DISTANCE_MATRIX
WHERE ICAO_FROM = 'LDZA'
ORDER BY DIST_TOT
LIMIT 15
OFFSET 0;

SELECT ICAO, NAME, ISO_COUNTRY, COORDINATES
FROM AIRPORTS
ORDER BY ICAO
LIMIT 3
OFFSET 2;
