CREATE TABLE AIRPORTS (
	ICAO VARCHAR(10) NOT NULL,
	"TYPE" VARCHAR(30) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	ELEVATION_FT VARCHAR(10),
	CONTINENT VARCHAR(30),
	ISO_COUNTRY VARCHAR(30),
	ISO_REGION VARCHAR(10),
	MUNICIPALITY VARCHAR(30),
	GPS_CODE VARCHAR(10) NOT NULL,
	IATA_CODE VARCHAR(10) NOT NULL,
	LOCAL_CODE VARCHAR(10) NOT NULL,
	COORDINATES VARCHAR(30) NOT NULL,
	PRIMARY KEY (ICAO)
);

CREATE TABLE AIRPORTS_DISTANCE_MATRIX (
	ICAO_FROM VARCHAR(10) NOT NULL,
	ICAO_TO VARCHAR(10) NOT NULL,
	COUNTRY VARCHAR(30),
	DIST_CTRY FLOAT,
	DIST_TOT FLOAT,
	NOTE VARCHAR(30),
	PRIMARY KEY (ICAO_FROM, ICAO_TO, COUNTRY),
	FOREIGN KEY (ICAO_FROM) REFERENCES AIRPORTS(ICAO),
	FOREIGN KEY (ICAO_TO) REFERENCES AIRPORTS(ICAO)
);

CREATE ROLE APLIKACIJA;

GRANT APLIKACIJA TO "nwtis_1";

GRANT SELECT, UPDATE, INSERT ON TABLE AIRPORTS TO APLIKACIJA;
GRANT SELECT, UPDATE, INSERT ON TABLE AIRPORTS_DISTANCE_MATRIX TO APLIKACIJA;

SELECT * FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES;


